__include__: "darts.yaml" # defaults are loaded from this file

# XNAS's parameters
nas:
    search:
        loader:
            train_batch: 64
        trainer:
            grad_clip: 1.0
            epochs: 50
            optimizer:
                type: "sgd"
                lr: 0.025
                decay: 0.0
                momentum: 0.0
                nesterov: False
                warmup: null
            
